# Generated by Django 3.1.4 on 2020-12-29 14:38

import ckeditor.fields
import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Bakı', 'Bakı'), ('Gəncə', 'Gəncə'), ('Naxçıvan', 'Naxçıvan'), ('Xankəndi', 'Xankəndi'), ('Lənkəran', 'Lənkəran'), ('Mingəçevir', 'Mingəçevir'), ('Naftalan', 'Naftalan'), ('Sumqayıt', 'Sumqayıt'), ('Şəki', 'Şəki'), ('Şirvan', 'Şirvan'), ('Yevlax', 'Yevlax')], max_length=100)),
                ('car_title', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('body_style', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('engine', models.IntegerField()),
                ('engine_hp', models.IntegerField()),
                ('fuel', models.CharField(choices=[('Benzin', 'Benzin'), ('Dizel', 'Dizel'), ('Hybrid', 'Hybrid'), ('Qaz', 'Qaz')], max_length=100)),
                ('mileage', models.IntegerField()),
                ('transmission', models.CharField(max_length=255)),
                ('drive_wheel', models.CharField(choices=[('Tam', 'Tam'), ('Arxa', 'Arxa'), ('Qabaq', 'Qabaq')], max_length=255)),
                ('no_of_owners', models.CharField(choices=[('Bəli', 'Beli'), ('Xeyr', 'Xeyr')], max_length=255)),
                ('price', models.IntegerField()),
                ('description', ckeditor.fields.RichTextField()),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[('Kruiz Kontrol', 'Kruiz Kontrol'), ('Arxa görüntü kamerası', 'Arxa görüntü kamerası'), ('Dəri salon', 'Dəri salon'), ('Parca salon', 'Parca salon'), ('Park radarı', 'Park radarı'), ('Lyuk', 'Lyuk'), ('Kondisioner', 'Kondisioner'), ('Auto Start Stop', 'Auto Start Stop'), ('Bluetooth', 'Bluetooth'), ('Airbag', 'Airbag'), ('Oturacaqların ventilyasiyası', 'Oturacaqların ventilyasiyası'), ('Oturacaqların isidilməsi', 'Oturacaqların isidilməsi')], max_length=174)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_featured', models.BooleanField(default=False)),
                ('car_photo1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
